// Autogenerated from Pigeon (v9.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface SumRequest ()
+ (SumRequest *)fromList:(NSArray *)list;
+ (nullable SumRequest *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface SumReply ()
+ (SumReply *)fromList:(NSArray *)list;
+ (nullable SumReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation SumRequest
+ (instancetype)makeWithA:(nullable NSNumber *)a
    b:(nullable NSNumber *)b {
  SumRequest* pigeonResult = [[SumRequest alloc] init];
  pigeonResult.a = a;
  pigeonResult.b = b;
  return pigeonResult;
}
+ (SumRequest *)fromList:(NSArray *)list {
  SumRequest *pigeonResult = [[SumRequest alloc] init];
  pigeonResult.a = GetNullableObjectAtIndex(list, 0);
  pigeonResult.b = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable SumRequest *)nullableFromList:(NSArray *)list {
  return (list) ? [SumRequest fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.a ?: [NSNull null]),
    (self.b ?: [NSNull null]),
  ];
}
@end

@implementation SumReply
+ (instancetype)makeWithResult:(nullable NSNumber *)result {
  SumReply* pigeonResult = [[SumReply alloc] init];
  pigeonResult.result = result;
  return pigeonResult;
}
+ (SumReply *)fromList:(NSArray *)list {
  SumReply *pigeonResult = [[SumReply alloc] init];
  pigeonResult.result = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable SumReply *)nullableFromList:(NSArray *)list {
  return (list) ? [SumReply fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.result ?: [NSNull null]),
  ];
}
@end

@interface SumApiCodecReader : FlutterStandardReader
@end
@implementation SumApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [SumReply fromList:[self readValue]];
    case 129: 
      return [SumRequest fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface SumApiCodecWriter : FlutterStandardWriter
@end
@implementation SumApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[SumReply class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[SumRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface SumApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation SumApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[SumApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[SumApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *SumApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    SumApiCodecReaderWriter *readerWriter = [[SumApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SumApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SumApi.sum"
        binaryMessenger:binaryMessenger
        codec:SumApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sumRequest:error:)], @"SumApi api (%@) doesn't respond to @selector(sumRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        SumRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        SumReply *output = [api sumRequest:arg_request error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
