// Autogenerated from Pigeon (v9.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class SumRequest;
@class SumReply;

@interface SumRequest : NSObject
+ (instancetype)makeWithA:(nullable NSNumber *)a
    b:(nullable NSNumber *)b;
@property(nonatomic, strong, nullable) NSNumber * a;
@property(nonatomic, strong, nullable) NSNumber * b;
@end

@interface SumReply : NSObject
+ (instancetype)makeWithResult:(nullable NSNumber *)result;
@property(nonatomic, strong, nullable) NSNumber * result;
@end

/// The codec used by SumApi.
NSObject<FlutterMessageCodec> *SumApiGetCodec(void);

@protocol SumApi
- (nullable SumReply *)sumRequest:(SumRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SumApi> *_Nullable api);

NS_ASSUME_NONNULL_END
