// Autogenerated from Pigeon (v9.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class MemoryResult {
  MemoryResult({
    this.usedMemory,
  });

  double? usedMemory;

  Object encode() {
    return <Object?>[
      usedMemory,
    ];
  }

  static MemoryResult decode(Object result) {
    result as List<Object?>;
    return MemoryResult(
      usedMemory: result[0] as double?,
    );
  }
}

class _MemoryApiCodec extends StandardMessageCodec {
  const _MemoryApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MemoryResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MemoryResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MemoryApi {
  /// Constructor for [MemoryApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MemoryApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _MemoryApiCodec();

  Future<MemoryResult> getMemoryInfo() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.MemoryApi.getMemoryInfo', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as MemoryResult?)!;
    }
  }
}

class _MemoryCallbackCodec extends StandardMessageCodec {
  const _MemoryCallbackCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MemoryResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MemoryResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class MemoryCallback {
  static const MessageCodec<Object?> codec = _MemoryCallbackCodec();

  void onReceivedMemoryInfo(MemoryResult result);

  static void setup(MemoryCallback? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.MemoryCallback.onReceivedMemoryInfo', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.MemoryCallback.onReceivedMemoryInfo was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MemoryResult? arg_result = (args[0] as MemoryResult?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.MemoryCallback.onReceivedMemoryInfo was null, expected non-null MemoryResult.');
          api.onReceivedMemoryInfo(arg_result!);
          return;
        });
      }
    }
  }
}
